// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfduBCZ1uQDdu0iNhuST7-jeI-Y8sTCjQ',
    appId: '1:263464131065:web:f4617053ef5793e0960528',
    messagingSenderId: '263464131065',
    projectId: 'loop-df308',
    authDomain: 'loop-df308.firebaseapp.com',
    storageBucket: 'loop-df308.appspot.com',
    measurementId: 'G-7R9TBF1Y8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpxJ79XCnl4r8xTAkhM_sn-thbdJLuJxw',
    appId: '1:263464131065:android:ffdb081c21b2fb72960528',
    messagingSenderId: '263464131065',
    projectId: 'loop-df308',
    storageBucket: 'loop-df308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQfBY-bf6jULgtT8_vorBAI7NyZNOP63o',
    appId: '1:263464131065:ios:03044e73496c38c1960528',
    messagingSenderId: '263464131065',
    projectId: 'loop-df308',
    storageBucket: 'loop-df308.appspot.com',
    iosBundleId: 'com.vanka.loop.loop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQfBY-bf6jULgtT8_vorBAI7NyZNOP63o',
    appId: '1:263464131065:ios:03044e73496c38c1960528',
    messagingSenderId: '263464131065',
    projectId: 'loop-df308',
    storageBucket: 'loop-df308.appspot.com',
    iosBundleId: 'com.vanka.loop.loop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfduBCZ1uQDdu0iNhuST7-jeI-Y8sTCjQ',
    appId: '1:263464131065:web:95724e72d0eb895b960528',
    messagingSenderId: '263464131065',
    projectId: 'loop-df308',
    authDomain: 'loop-df308.firebaseapp.com',
    storageBucket: 'loop-df308.appspot.com',
    measurementId: 'G-8PZJTR7RVT',
  );
}
